version: "1.1"
   
services:
  app:
    build: .
    container_name: english_land_app
    command: python manage.py runserver 0.0.0.0:80
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres:15.4-alpine
    container_name: english_land_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/