# Generated by Django 4.0.4 on 2022-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_words', '0002_rename_words_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='status',
            field=models.CharField(choices=[('studied', 'studied'), ('on study', 'on study')], default='on study', max_length=15),
        ),
    ]
