# Generated by Django 4.0.4 on 2022-08-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_words', '0003_alter_train_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, choices=[('NOUN', 'noun'), ('VERB', 'verb'), ('ADJECTIVE', 'adjective'), ('ADVERB', 'adverb'), ('PRONOUN', 'pronoun'), ('OTHER', 'other'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=15),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='russian',
            field=models.CharField(max_length=100),
        ),
    ]
