# Generated by Django 4.0.4 on 2022-08-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_words', '0005_rename_user_id_train_user_rename_world_id_train_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='last_try',
            field=models.DateField(auto_now=True),
        ),
    ]
