# Generated by Django 4.0.4 on 2022-08-29 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_words', '0006_train_last_try'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WordRussian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='train',
            name='status',
        ),
        migrations.AddField(
            model_name='train',
            name='is_studied',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WordEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100, unique=True)),
                ('translates', models.ManyToManyField(through='new_words.Vocabulary', to='new_words.wordrussian')),
            ],
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_words.wordenglish'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='russian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_words.wordrussian'),
        ),
        migrations.CreateModel(
            name='TrainOld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_ans_cnt', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('studied', 'studied'), ('on study', 'on study')], default='on study', max_length=15)),
                ('last_try', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_words.word')),
            ],
        ),
        migrations.AlterField(
            model_name='train',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_words.wordenglish'),
        ),
    ]
