# Generated by Django 4.0.4 on 2022-08-31 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_words', '0008_vocabulary_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='english',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='new_words.wordenglish', verbose_name='english_word_tb'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='russian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to='new_words.wordrussian', verbose_name='russian_word_tb'),
        ),
        migrations.DeleteModel(
            name='TrainOld',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
