# Generated by Django 4.0.4 on 2022-09-19 15:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('new_words', '0009_alter_vocabulary_english_alter_vocabulary_russian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='incorrect_ans_cnt',
            field=models.IntegerField(default=0, verbose_name='Неверных ответов'),
        ),
        migrations.AddField(
            model_name='train',
            name='priority',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='train',
            name='correct_ans_cnt',
            field=models.IntegerField(default=0, verbose_name='Верных ответов'),
        ),
        migrations.AlterField(
            model_name='train',
            name='is_studied',
            field=models.BooleanField(default=False, verbose_name='Изучено'),
        ),
        migrations.AlterField(
            model_name='train',
            name='last_try',
            field=models.DateField(auto_now=True, verbose_name='Дата последней попытки'),
        ),
        migrations.AlterField(
            model_name='train',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='train',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_words.wordenglish', verbose_name='Слово'),
        ),
    ]
