# Generated by Django 4.0.4 on 2022-08-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_words', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
    ]
