# Generated by Django 4.0.4 on 2022-08-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_words', '0004_word_category_alter_word_english_alter_word_russian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='train',
            old_name='world_id',
            new_name='word',
        ),
        migrations.AddField(
            model_name='train',
            name='correct_ans_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(choices=[('NOUN', 'noun'), ('VERB', 'verb'), ('ADJECTIVE', 'adjective'), ('ADVERB', 'adverb'), ('PARTICIPLE', 'participle'), ('PRONOUN', 'pronoun'), ('OTHER', 'other'), ('UNKNOWN', 'unknown')], default='UNKNOWN', max_length=15),
        ),
    ]
